import java.util.Scanner;

import javax.sound.midi.SysexMessage;

public class juegoLogico {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		Scanner sc = new Scanner(System.in);
		System.out.println("Elige entre:\n -Piedra\n -Papel\n -Tijeras ");
		String select = sc.nextLine();
		/*
		 Crearemos una herramienta capaz de generar un numero aleatorio
		 Math.random nos da un numero random entre 1 y 0, basicamente puede ser cualquier numero
		 
		 si queremos que este numero este compreendido entre 1 y 3 realizamos lo siguiente: 
		  */
		int n = (int) ((Math.random()*3)+1);
		/*
		 -El (int) es necesario para convertir la salida del Math a un int, ya que siempre nos devuelve
		 un double.
		 
		 -Se escribe asi el Math, porque, en java y en la programación 1 equivale a 0, siendo así
		 5 = 4, pero para burlarlo solo hacemos el +1 y como queremos generar un numero de 1 a 3
		 
		 */
		String eleccionIA;//sera la seleccion que sale del random, es un numero generado por software
		
		switch(n) {
		case 1: eleccionIA="piedra"; break;
		case 2: eleccionIA="papel"; break;
		default: eleccionIA="tijeras"; break; }
		/*Crea tosas las resultantes posibles,  y al final un else por si no se escribe correctamente la entrada*/
		
		if(select.toLowerCase().equals("piedra")&& eleccionIA.equals("tijeras")) {
			System.out.println("Piedra revienta a las tijeras...Has ganado!-muerte a todas las tijeras-");
		}else if(select.toLowerCase().equals("tijeras")&& eleccionIA.equals("piedra")) {
			System.out.println("Has perdido, las tijeras no pueden cortar la dura piedra.");
		}else if(select.toLowerCase().equals("piedra")&& eleccionIA.equals("papel")) {
			System.out.println("Vaya, de alguna manera el papel le gana a la piedra, una locura pero... has perdido.");
		}else if(select.toLowerCase().equals("tijeras")&& eleccionIA.equals("papel")) {
			System.out.println("Debil tijeras, pero mas debil el papel, ganaste, joven");
		}else if(select.toLowerCase().equals("papel")&& eleccionIA.equals("piedra")) {
			System.out.println("Papel gana a piedra, la revienta a la piedra.");
		}else if(select.toLowerCase().equals("papel")&& eleccionIA.equals("tijeras")) {
			System.out.println("Tu papel se cortó, ya nada, has perdido.");
		}else if(select.toLowerCase().equals(eleccionIA.toLowerCase())) {
			System.out.println("Empate, tu "+select+" se choca con "+eleccionIA+", pero ninguno gana, son iguales de alma y cuerpo ");
		}else {
			System.out.println("Na esto no funciona.");
		}	
	}//main
	
}
/*
English Version
 
 import java.util.Scanner;

public class juegoLogico {

    public static void main(String[] args) {
        
        // We will create a tool capable of generating a random number
        // Math.random gives us a random number between 1 and 0, basically, it can be any number.
        // If we want this number to be between 1 and 3, we do the following:
        
        int n = (int) ((Math.random() * 3) + 1);
        
        // The (int) is necessary to convert the output of Math to an int, since it always returns
        // a double.
        // Math is written this way because, in Java and programming, 1 equals 0, so
        // 5 = 4, but to bypass this, we just add +1, and since we want to generate a number from 1 to 3,
        
        String eleccionIA; // This will be the selection generated by the random number, a number generated by software
        
        switch (n) {
            case 1: eleccionIA = "piedra"; break;
            case 2: eleccionIA = "papel"; break;
            default: eleccionIA = "tijeras"; break;
        }
        
        // Creates all possible outcomes, and at the end an else if the input is not written correctly
        
        if (select.toLowerCase().equals("piedra") && eleccionIA.equals("tijeras")) {
            System.out.println("Piedra revienta a las tijeras...Has ganado!-muerte a todas las tijeras-");
        } else if (select.toLowerCase().equals("tijeras") && eleccionIA.equals("piedra")) {
            System.out.println("Has perdido, las tijeras no pueden cortar la dura piedra.");
        } else if (select.toLowerCase().equals("piedra") && eleccionIA.equals("papel")) {
            System.out.println("Vaya, de alguna manera el papel le gana a la piedra, una locura pero... has perdido.");
        } else if (select.toLowerCase().equals("tijeras") && eleccionIA.equals("papel")) {
            System.out.println("Debil tijeras, pero mas debil el papel, ganaste, joven");
        } else if (select.toLowerCase().equals("papel") && eleccionIA.equals("piedra")) {
            System.out.println("Papel gana a piedra, la revienta a la piedra.");
        } else if (select.toLowerCase().equals("papel") && eleccionIA.equals("tijeras")) {
            System.out.println("Tu papel se cortó, ya nada, has perdido.");
        } else if (select.toLowerCase().equals(eleccionIA.toLowerCase())) {
            System.out.println("Empate, tu " + select + " se choca con " + eleccionIA + ", pero ninguno gana, son iguales de alma y cuerpo ");
        } else {
            System.out.println("Na esto no funciona.");
        }   
    } // main

}



  */


